[package]
name = "hyper-server"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

[dependencies]
tokio-core = "*"
hyper = "*"
futures = "*"
pretty_env_logger = "*"
rand = "*"
log = "*"